from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class QueryRequest(BaseModel):
    question: str = Field(..., description="The user query to retrieve context for and answer")

class SourceCitation(BaseModel):
    text: str = Field(..., description="The text content of the retrieved chunk")
    document_name: str = Field(..., description="The name of the source PDF file")
    similarity_score: float = Field(..., description="The normalized similarity score (0 to 1)")
    page: Optional[int] = Field(None, description="The page number where the chunk is located")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The context-grounded response generated by the AI")
    sources: List[SourceCitation] = Field(default=[], description="List of retrieved source chunks with citations")
    latency_ms: Optional[float] = Field(None, description="Retrieval and processing latency in milliseconds")

class DocumentMetadata(BaseModel):
    fileName: str = Field(..., description="Name of the PDF file")
    fileSize: int = Field(..., description="File size in bytes")
    chunksCount: int = Field(..., description="Number of semantic chunks generated")

class SummaryRequest(BaseModel):
    fileName: str = Field(..., description="Name of the document to summarize")

class SummaryResponse(BaseModel):
    summary: str = Field(..., description="AI-generated summary of the document")
